services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build: ./backend
    ports:
      - "4000:4000"
    env_file: .env
    depends_on:
      - mongo

  web:
    build: ./frontend
    ports:
      - "5173:5173"
    env_file: .env
    depends_on:
      - api
volumes:
  mongo_data:
